config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :streamers
  resources :events, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# Event model
class Event < ApplicationRecord
  enum event_type: %i[follow subscribe]

  belongs_to :streamer, primary_key: 'name', foreign_key: 'streamer_name'

  after_commit :broadcast_new_event, on: :create

  def self.create_upon_webhook(subscription_params, event_params)
    create do |event|
      event.streamer_name = event_params[:broadcaster_user_name].downcase
      event.event_type = subscription_params[:type].split('.').last
      event.viewer_name = event_params[:user_name]
    end
  end

  private

  # Broadcast new event to the streamer page
  def broadcast_new_event
    Pusher.trigger("#{streamer_name}-channel", 'new-event', {
      event_id: id,
      event_type: event_type,
      viewer_name: viewer_name
    })
  end
end

app/models/streamer.rb
# Streamer model
class Streamer < ApplicationRecord
  include AASM

  has_many :events, primary_key: 'name', foreign_key: 'streamer_name', dependent: :destroy

  validates :name, presence: true, uniqueness: true

  aasm(:status) do
    state :off, initial: true
    state :live

    event :stream, after: :initiate_event_listeners do
      transitions from: :off, to: :live, guard: :can_go_live?
    end

    event :stop, after: :kill_event_listeners do
      transitions from: :live, to: :off
    end
  end

  def can_go_live?
    Streamer.live.count.zero?
  end

  def initiate_event_listeners
    twitch.subscribe_to_follows_events
    twitch.subscribe_to_subscriptions_events
  end

  def kill_event_listeners
    twitch.delete_subscriptions
  end

  private

  def twitch
    @twitch ||= TwitchService.new(name)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[twitch]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :unauthorized_resource_redirect

  private

  def unauthorized_resource_redirect
    redirect_to root_path if devise_controller? && resource_name == :user && action_name == 'new'
  end
end

app/controllers/events_controller.rb
# Events controller
class EventsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    Event.create_upon_webhook(subscription_params, event_params) unless params[:event].empty?
    render plain: params['challenge'], status: :ok
  end

  private

  def subscription_params
    params.require(:subscription).permit(:type)
  end

  def event_params
    params.require(:event).permit(:user_name, :broadcaster_user_id, :broadcaster_user_name)
  end
end

app/controllers/home_controller.rb
# Home controller
class HomeController < ApplicationController
  def index
    @live_streamer = Streamer.live.first
  end

  def streamer; end
end

app/controllers/streamers_controller.rb
# Streamers controller
class StreamersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_streamer, only: :show

  def index
    # Total number of events received by each streamer
    @events_by_streamer = Event.group(:streamer_name).count.to_a
    # Count of events by event_type and streamer name
    @count_of_events = Event.group(:streamer_name, :event_type).count.to_a.map(&:flatten)
  end

  def show
    @events = @live_streamer.events.order(created_at: :desc).limit(10)
  end

  def create
    streamer = Streamer.find_or_initialize_by(streamer_params)
    if streamer.stream!
      redirect_to root_path, notice: "You're now live-following your favorite streamer."
    else
      redirect_to root_path, alert: 'Something went wrong.'
    end
  end

  def update
    streamer = Streamer.find(params[:id])
    if streamer.stop!
      redirect_to root_path, notice: "You've stopped live-following your favorite streamer."
    else
      redirect_to root_path, alert: 'Something went wrong.'
    end
  end

  private

  def streamer_params
    params.require(:streamer).permit(:name)
  end

  def set_streamer
    @live_streamer = Streamer.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# Application's callback method
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :twitch

  def twitch
    @user = User.from_omniauth(auth_data)
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Twitch') if is_navigational_format?
    else
      session['devise.twitch_data'] = auth_data
      redirect_to root_path, alert: 'User could not be authenticated.'
    end
  end

  def failure
    redirect_to root_path
  end

  private

  def auth_data
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include NavigationHelper
  include HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def home_content_partial_path
    if user_signed_in?
      'home/user_signed_in_content'
    else
      'home/non_signed_in_content'
    end
  end
end

app/helpers/navigation_helper.rb
# Navigation Helper
module NavigationHelper
  def navigation_partial_path
    if user_signed_in?
      'layouts/navigation/user_signed_in_links'
    else
      'layouts/navigation/non_signed_in_links'
    end
  end
end

app/views/home/_non_signed_in_content.html.erb
<h1 class="cover-heading">Streamer Event Viewer</h1>
<p class="lead">
  SEV is an app that allows you to see your favorite streamer's Twitch events in real-time.<br />
  Sign in and enjoy a livestream, chat and the most recent events of your favorite streamer.
</p>
<p class="lead">
  <%= link_to 'Sign in with Twitch', user_twitch_omniauth_authorize_path, class: 'btn btn-lg btn-secondary' %>
</p>

app/views/home/_user_signed_in_content.html.erb
<% if @live_streamer.present? %>
  <p>You're currently live-following:</p>

  <div class="d-flex justify-content-around align-items-center">
    <%= link_to @live_streamer.name, streamer_path(@live_streamer) %>
    <%= link_to 'Stop', streamer_path(@live_streamer), class: 'btn btn-light btn-sm', method: :put, data: { confirm: 'Are you sure?' } %>
  </div>

<% else %>
  <%= form_for(:streamer, url: streamers_path, html: { class: 'text-left' }) do |f| %>
    <%= f.label :name, "STREAMER NAME" %>
    <div class="d-flex">
      <%= f.text_field :name, placeholder: "Enter your favorite streamer's name", class: "form-control", required: true %>
      <%= f.submit 'Submit', class: 'btn btn-outline-light ml-2' %>
    </div>
  <% end %>
<% end %>

app/views/home/index.html.erb
<main role="main" class="inner cover text-center mt-4 mb-auto">
  <%= render home_content_partial_path %>
</main>

app/views/layouts/_flash_messages.html.erb
<div id="flash">
  <% flash.each do |key, value| %>
    <% if flash[:notice].present? %>
      <div class="alert alert-success fade show" role="alert">
        <strong style="color: #5cb85c;">Great! </strong><%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if flash[:alert].present? %>
      <div class="alert alert-danger fade show" role="alert">
        <strong style="color: #d9534f;">Sorry! </strong><%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Streamer Event Viewer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Twitch JS -->
    <script src="https://embed.twitch.tv/embed/v1.js"></script>

    <!-- Pusher JS -->
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>

    <!-- Google Charts JS -->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  </head>

  <body>
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="masthead">
        <div class="inner">
          <h3 class="masthead-brand">SEV</h3>
          <%= render navigation_partial_path %>
        </div>
      </header>
      <%= render 'layouts/flash_messages' %>
    <%= yield %>
    </div>
  </body>

  <!-- Bootstrap JS -->
  <!-- jQuery and JS bundle w/ Popper.js -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</html>

app/views/layouts/navigation/_non_signed_in_links.html.erb
<nav class="nav nav-masthead justify-content-center">
  <%= link_to 'Home', root_path, class: 'nav-link active'%>
</nav>

app/views/layouts/navigation/_user_signed_in_links.html.erb
<nav class="nav nav-masthead">
  <li class="nav-item mr-3">
    <%= active_link_to 'Home', root_path, class: 'nav-link', active: :exclusive %>
  </li>
  <% if @live_streamer.present? %>
    <li class="nav-item mr-3">
      <%= active_link_to 'Streamer', streamer_path(@live_streamer), class: 'nav-link', active: :exclusive %>
    </li>
  <% end %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <img src="<%= current_user.image %>" alt="profile_picture" height="25">
      <span class="ml-1"><%= current_user.name %></span>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <small class="dropdown-item disabled"><%= current_user.email %></small>
      <%= link_to 'Reports', streamers_path, class: 'dropdown-item' %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
    </div>
  </li>
</nav>

app/views/streamers/index.html.erb
<div class="total mb-4">
  <p class="lead">1. Total number of events received by each streamer</p>
  <div id="total-chart"></div>
</div>
<div class="counts mt-4">
  <p class="lead">2. Count of events by event_type and streamer name</p>
  <div id="count-chart"></div>
</div>

<script>
  google.charts.load('current', {packages: ['corechart']});
  google.charts.setOnLoadCallback(drawCharts);

  function drawTotalEventsChart() {
    var data = google.visualization.arrayToDataTable([
      ['streamer', 'events'],
    ].concat(<%= raw @events_by_streamer %>));

    var options = {
      haxis: {
        title: 'streamer'
      },
      vaxis: {
        title: 'events_number'
      }
    };

    var chart = new google.visualization.AreaChart(
      document.getElementById('total-chart')
    );
    chart.draw(data, options);
  }

  function drawCountOfEvents() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Streamer');
    data.addColumn('string', 'Event type');
    data.addColumn('number', 'Event number');
    data.addRows(<%= raw @count_of_events %>);

    var options = {
      "title": "Count of events by event_type and streamer name",
      "cssClassNames": { "headerRow": "text-black", "tableCell": "text-black" }
    };

    google.visualization.drawChart({
      "chartType": "Table",
      "containerId": "count-chart",
      "options": options,
      "dataTable": data
    });
  }

  function drawCharts() {
    drawTotalEventsChart();
    drawCountOfEvents();
  }
</script>

app/views/streamers/show.html.erb
<div class="sisa d-flex justify-content-between">
  <div id="events-container">
    <p>Recent events: </p>
    <ul id="events-list" class="mr-4">
      <% @events.each do |event| %>
        <li class="events-list-item" id="<%= event.id %>">new <%= event.event_type %>: <%= event.viewer_name %></li>
      <% end %>
    </ul>
  </div>
  <div id="twitch-embed"></div>
</div>

<script type="text/javascript">
  new Twitch.Embed("twitch-embed", {
    width: 754,
    height: 450,
    channel: "<%= @live_streamer.name %>"
  });
</script>

<script>
  var pusher = new Pusher('<%= Rails.application.credentials.dig(:pusher, :key) %>', {
    cluster: '<%= Rails.application.credentials.dig(:pusher, :cluster) %>',
    encrypted: true
  });

  var channel = pusher.subscribe('<%= @live_streamer.name %>-channel');
  var container = document.getElementById('events-list');

  channel.bind('new-event', function(data) {
    let event_id = data.event_id;
    let event_type = data.event_type;
    let viewer_name = data.viewer_name;
    let new_list_item = document.createElement('li');
    new_list_item.id = event_id;
    new_list_item.className = 'events-list-item';
    new_list_item.innerHTML = `new ${event_type}: ${viewer_name}`;
    new_list_item.style.display = 'none';
    if (container.getElementsByTagName("li").length == 10){
      $('#events-list li:last-child').remove();
    }
    container.insertBefore(new_list_item, container.firstChild);
    $(`#${event_id}`).show('slow');
  });
</script>